# playbook to power on ESXi, start vCenter, and associated VMs

# As of now, I only have one environment setup in here, but in 
# the future I might use labels/tags to power up certain things.
---
- name: power up homelab
  hosts: all
  gather_facts: false

  tasks:
  - name: power on ESXi host via iLO
    community.general.ipmi_power:
      name: ilo.homelab
      user: "{{ ilo_username }}"
      password: "{{ ilo_password }}"
      state: 'on'
    delegate_to: localhost

  - name: wait for ESXi to respond on the network
    ansible.builtin.uri:
      url: "https://esxi.homelab"
      return_content: true
      validate_certs: false
      status_code:
        - 200
    until: uri_output.status == 200
    retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
    delay: 30 # Every 5 seconds
    register: uri_output
    delegate_to: localhost

  - name: wait for ESXi services to come online
    community.vmware.vmware_vm_info:
      validate_certs: false
      hostname: "esxi.homelab"
      username: "{{ esxi_username  }}"
      password: "{{ esxi_password }}"
    delegate_to: localhost
    register: all_vms

  - name: power up vCenter
    community.vmware.vmware_guest_powerstate:
      hostname: "esxi.homelab"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      validate_certs: false
      name: "vcsa.homelab"
      state: powered-on
    register: vcsa_power_on
    delegate_to: localhost
  
  - name: wait for VMware tools to come up
    community.vmware.vmware_guest_tools_wait:
      hostname: "esxi.homelab"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      validate_certs: false
      name: "vcsa.homelab"
    delegate_to: localhost
  
  - name: wait for vCenter to not return 503
    ansible.builtin.uri:
      url: "https://vcsa.homelab"
      return_content: true
      validate_certs: false
      status_code:
        - 200
    until: uri_output.status == 200
    retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
    delay: 30 # Every 5 seconds
    register: uri_output
    delegate_to: localhost

  - name: power up VMs
    community.vmware.vmware_guest_powerstate:
      hostname: "vcsa.homelab"
      username: "{{ vc_username }}"
      password: "{{ vc_password }}"
      validate_certs: false
      name: "{{ item }}"
      state: powered-on
    register: vcsa_power_on
    delegate_to: localhost
    loop:  
      - dc01
      - opnsense
      - pth1
      - ubuntu01
